### ISSUE TITLE
UTHash works like a charm on ARM (Android), please add it to the platforms list :-)

### ISSUE THREAD

**Issue by silvioprog** [troydhanson/uthash#103]
Hello masters,

Thanks for this awesome library! It worked like a charm for my ARMv7 and finally I can use an efficient C hash table in my Android (tested on version 5 and 6) application. My C structure is just a table saving function pointers (providing aliases to the FFI library) that can be found by a string key, so uthash was the perfect choice for implementing that.

So, could you add the `Android` item in the [uthash's platforms list](http://troydhanson.github.io/uthash/userguide.html#_c_c_and_platforms)? If you prefer I can send a step-by-step text showing how to integrate the uthash sample to the [official Google's `hello-jni` example](https://github.com/googlesamples/android-ndk/tree/master/hello-jni).

Thank you! :+1:

**Comment by troydhanson** [comment]
thanks Silvio I'm glad to hear it worked well for you!
