### ISSUE TITLE
Openwrt segmentation fault

### ISSUE THREAD

**Issue by DRTEK** [troydhanson/uthash#107]
Hello 
first of all thank you very much for your hard work on such a good library 
i have a c code it compiles and runs fine on ubuntu x64 machine but for somereason when i hit the call of one of your macros it gives me segmantation fault , (i am hoping that i am wrong for it is not compatible with mipsel devices and only my code is wrong ) can you please give this a snippet a look tell me what i am missing 
thanks alot
MK

when i call this below function 
it gives me segmantation fault only on mipsel devices / openwrt 

int add_nas_device_to_table(reclient *device) {
	if (find_nas_device_by_deviceid(device->nas_id) == NULL) {
		HASH_ADD(hh, nasdevices, nas_id, strlen(device->nas_id), device);
		return 0;
	}
	else {
		return -1;
	}
}

**Comment by Quuxplusone** [comment]
Hi @DRTEK,

I'd need to see much more of your code to diagnose the problem; for example, who calls `add_nas_device_to_table`, and where is the definition of `reclient`, and so on.

But at a glance, I suspect that you're using `HASH_ADD` when you should be using `HASH_ADD_KEYPTR`.

If you figure it out, please close this issue. I'll leave it open for now.
