### ISSUE TITLE
Using uthash inside a kernel module

### ISSUE THREAD

**Issue by alexandernst** [troydhanson/uthash#11]
Since none of string.h, stddef.h nor stdlib.h are available in a kernel module, is there a way for this library to be used in one? If "yes", how?

EDIT:  BTW, I saw https://github.com/dbellavista/edfomai/blob/master/datastructures/uthash.h which kind of does what I want, but it's integrated with rtdm_driver.h. I could clean that and use it on my project, but it would be nice if you could merge their changes so your project can compile on both userspace and kernelspace projects :)

**Comment by GreatFireWall** [comment]
Does it implementation ?
