### ISSUE TITLE
HASH_SORT2(head,cmpfcn,cmpcls)

### ISSUE THREAD

**Issue by silvioprog** [troydhanson/uthash#110]
Hello masters,

Sometimes we need to change the sorting logic at run-time, however, the `HASH_SORT` doesn't offer any way to do that, unless using global variables (argh...). So, what do you think about adding a `HASH_SORT2` macro allowing the programmer to send a closure in a third parameter? We could reuse the code, moving all `HASH_SORT`'s implementation into `HASH_SORT2`, so the `HASH_SORT` would change to something like `#define HASH_SORT(head,cmpfcn) HASH_SORT2(head,cmpfcn,NULL)`, and finally we would able to do something like this pseudo code below:

```c
static int cmp_func(void *cls, void *a, void *b) {
  struct my_order *order = cls;
  struct my_type *ta = a;
  struct my_type *tb = b;
  switch (order->by) {
    case name_asc: return strcmp(ta->name, tb->name);
    case name_desc: return -strcmp(ta->name, tb->name);
    case value_asc: return strcmp(ta->value, tb->value);
    case value_desc: return -strcmp(ta->value, tb->value);
  }
}

...

struct my_order *order;
HASH_SORT2(hash, &cmp_func, order); // to use "order by"
```

**Comment by Quuxplusone** [comment]
You can do this today with `HASH_SORT`, or at least that's the intention:

    struct my_order *order;
    #define compare(a,b) cmp_func(order, a, b)
    HASH_SORT(hash, compare);
    #undef compare

So unless there's a case that that approach *can't* cover, I'm inclined to close this issue.

Btw, stylistically I'd recommend passing the cookie `cls` as your *third* argument, not the first, just because that's what the cookie-taking comparison function for [`qsort_r`](https://linux.die.net/man/3/qsort_r) does.

**Comment by silvioprog** [comment]
I'm not sure if a macro will help me because I need to export uthash as library to use it on other language that doesn't provide macros support, but I'm going to test it anyway and back with feed back ...

**Comment by Quuxplusone** [comment]
I noticed you mentioned a Python binding elsewhere. I'm curious to see how that's going to work anyway. But given that uthash is pretty much 100% macros, one more little macro (`compare(a,b)`) in your own code shouldn't be a problem. I think either *all* the macros are going to give you trouble, or none are.
Let me know how it goes.

**Comment by silvioprog** [comment]
Arthur, your suggestion solved my problem and now I have a sort callback with closure support. :-)

```c
BF_EXTERN bool bf_hs_sort(struct bf_hs **hsl, bf_hs_sort_cb cmp_cb, void *cmp_cls) __nonnull((1, 2));

...

bool bf_hs_sort(struct bf_hs **hsl, bf_hs_sort_cb cmp_cb, void *cmp_cls) {
    if (NULL == hsl || NULL == cmp_cb)
        return false;
#define CMP(a, b) cmp_cb(cmp_cls, a, b)
    HASH_SORT(*hsl, CMP);
#undef CMP
    return true;
}
```
Now I'm going to check the other issue about top/next.

Thank you very much dude! :-)
