### ISSUE TITLE
How can get List of array?

### ISSUE THREAD

**Issue by questionpython** [troydhanson/uthash#120]
Hello,
How can get List of array?

```
#include <stdio.h>
#include "utarray.h"
typedef struct example_user_t {
    int id;
    int cookie;
} example_user_t;
static UT_icd icd = {
    .sz = sizeof(example_user_t),
    .init = NULL,
    .copy = NULL,
    .dtor = NULL
};
int main()
{
    UT_array users;
    utarray_init(&users, &icd);
    for (int i=1; i<=100000000; i++)
    {
        example_user_t user = {i, i*i};
        utarray_push_back(&users, &user);
    }
    printf("%d\n",users.i);
    for (int i=1; i<=users.i;i++)
    {
```
Please Help me complate this place
-----------
```
    }

}
```
also how can remove a index from array? example `_remove(&users,5);`

**Comment by tbeu** [comment]
Did you already try utarray_next for the looping and utarray_erase for the removal?

**Comment by Quuxplusone** [comment]
@questionpython: This kind of "how do I do X with library Y" question is probably better suited to [StackOverflow](http://stackoverflow.com/questions/tagged/uthash), as opposed to opening an issue against the project every time you have a question.

Documentation for utarray is available [here](http://troydhanson.github.io/uthash/utarray.html#operations).
