### ISSUE TITLE
I would like to use this lib but I have to be MISRA conform

### ISSUE THREAD

**Issue by mgiaco** [troydhanson/uthash#132]
Dose someone have the same problem? Is there any bypass I can use?

many thanks

**Comment by Quuxplusone** [comment]
Hi @mgiaco! I won't have time to really look at this for a couple of weeks yet, but if you post the details here, I (or anyone else) can try to fix them in a patch.

The relevant details include:
- Your compiler (vendor and version)
- The exact command-line arguments you passed it (or as many of them as you can figure out; with particular attention to arguments that affect diagnostics)
- The exact diagnostic output of the compiler, i.e., the warnings you're trying to suppress
- What you've tried so far (e.g. does adding pragmas around the `#include` of "uthash.h" help? if it's complaining about the use of raw `unsigned`, did you try search-and-replacing `unsigned` to `uint32_t` and did that quiet any of the warnings? etc.)

**Comment by mgiaco** [comment]
Sorry i do not have the time to use that anymore but If I came back here I will report.
