### ISSUE TITLE
Serialization?

### ISSUE THREAD

**Issue by ArturFormella** [troydhanson/uthash#133]
Hello!
Is it possible to serialize hashmap to string? I need it to send app state to other thread and unserialize there.

**Comment by tbeu** [comment]
@troydhanson also created a serialization library https://github.com/troydhanson/tpl, which could do it.

**Comment by Quuxplusone** [comment]
I don't know any way of serializing a uthash hash other than the obvious

    myserializer_serialize_beginhashtable();
    HASH_ITER(myhash, cur, tmp) {
        myserializer_serialize_item(cur);
    }
    myserializer_serialize_endhashtable();

How to serialize each item in the hash is of course up to you; an item is just a C struct (which might contain pointers or even weirder unserializable data), so it's always going to be up to you to figure out how to serialize it correctly.

**Comment by tbeu** [comment]
Issue troydhanson/tpl#12 is a similar one.

**Comment by ArturFormella** [comment]
Is there any beter way to unserialize? It has complexity O(N*logN). I hope not worse...

```C++
for (i = 0; i<size; i++) {
  int32 key = readNextKeyFrom(serialized)
  int32 value = readNextValueFrom(serialized)
  hashMap *s = (hashMap*)malloc(sizeof(hashMap));
  if(s == NULL){
     elog(ERROR, "malloc error!"); 
  }else{
    s->value = value;
    s->id = key;
    HASH_ADD_INT( hashmap, id, s );
  }
}
```
Serialized keys are sorted. Is it possible to do it with O(N)?
(N = number of serialized keys)
