### ISSUE TITLE
Could not find HASH_ITER

### ISSUE THREAD

**Issue by nataniko** [troydhanson/uthash#136]
configure: error: Could not find HASH_ITER

**Comment by Quuxplusone** [comment]
Hi @nataniko. Can you add WAY more information? You say you have uthash "installed", but then you're apparently running `./configure`, which indicates that you're still trying to install something manually. And then on top of that, uthash doesn't use `./configure` for installation; it's a header-only library.

This might be an issue to take up with the person who packages uthash for your distribution. What distribution mechanism are you using? I just checked, and uthash doesn't seem to be available on Homebrew (`brew search uthash`). So whatever you're using, maybe it's misconfigured.

I also have a less arcane guess, but I'd like to see your detailed, reproducible bug report first.

**Comment by nataniko** [comment]
os x 10.13.1
uthash 2.0.2 installed with mac ports (sudo port install uthash)
I think it download package from the http://jog.id.packages.macports.org/macports/packages/uthash/

**Comment by Quuxplusone** [comment]
And what are you trying to `./configure` when you get the error?

**Comment by nataniko** [comment]
I want to make https://github.com/luke-jr/bfgminer

**Comment by nataniko** [comment]
try 
git clone https://github.com/nataniko/xgminer-osx-dev.git
cd xgminer-osx-dev/scripts
./init.sh

**Comment by Quuxplusone** [comment]
So, is `uthash.h` in your include path? (This was my "less arcane" guess. I was hoping you'd stumble onto it yourself.)
Try symlinking `/usr/include/uthash.h` to wherever your copy of `uthash.h` is installed. If you're still running into problems, I suggest asking over at https://github.com/luke-jr/bfgminer ; this sounds like "bfgminer has no tutorial for how to build on OSX with MacPorts" and not anything specific to uthash itself. I suspect that bfgminer would welcome a pull request to add such a tutorial, once you get it working.

P.S.: personally, I strongly advise switching to [Homebrew](https://brew.sh). :)

**Comment by nataniko** [comment]
thanx for advise. I will try to kill macports and reinstall things with Homebrew

**Comment by nataniko** [comment]
Update: homebrew can't install uthash. 
```
brew install uthash
Error: No available formula with the name "uthash
```

no way to use uthash with OS X :boom:
