### ISSUE TITLE
Error after macro substitution: Struct 'UT_hash_handle' doesn't have a field 'hh_prev'

### ISSUE THREAD

**Issue by silvioprog** [troydhanson/uthash#138]
Hello.

I have the following struct:

```c
struct b4r_hs {
    char *key, *name, *val;
    UT_hash_handle hh;
};
```

and the following function:

```c
bool b4r_hs_add(struct b4r_hs **hsl, const char *name, const char *val) {
    struct b4r_hs *hs;
    char *key;
    if (!(key = _B4R_HS_NEW_KEY(name)))
        return false;
    if (!(hs = _b4r_hs_new(key, name, val))) {
        _B4R_FREE(key);
        return false;
    }
    HASH_ADD_STR(*hsl, name, hs);
    return true;
}
```

However, I've noticed the following warning:

`Error after macro substitution: Struct 'UT_hash_handle' doesn't have a field 'hh_prev'`

![image](https://user-images.githubusercontent.com/1456829/34857871-e07b31c0-f72b-11e7-9f22-24978ad13a2e.png)

but according [uthash's User Guide](https://troydhanson.github.io/uthash/userguide.html#_your_structure) my struct is OK. So, what I'm doing wrong? :-/

(entire code available [here](https://github.com/brook-dev/brook4rest/blob/master/src/b4r_hs.c))

Edit:

Additional info: I'm using CLion on Xubuntu 16.04 (gcc 5.4 / clang 5.0).

**Comment by Quuxplusone** [comment]
Is this still a problem for you?  I don't see any errors when compiling your source file.

    git clone --recursive https://github.com/brook-dev/brook4rest
    cd brook4rest/src
    git checkout f675dbbe4ccfe07d9e075faba991a8050b1bc7d2
    clang b4r_hs.c -I ../include/ -I ../uthash/include/ '-D__nonnull(x)=' '-D__malloc=' -c

**Comment by Quuxplusone** [comment]
Feel free to reopen this issue if it's still unresolved.

**Comment by silvioprog** [comment]
Hi @Quuxplusone , thanks for replying. After your answer I've tried purely gcc/clang, but I can't reproduce it too. I don't know how CLion reports this warnings, but I'm still trying to find it, however, without success. :disappointed:

**Comment by silvioprog** [comment]
I sent a message to the JetBrains' team. Let's wait for an answer from them. :-)

**Comment by silvioprog** [comment]
Hello again @Quuxplusone . A JetBrains developer answered me with the following link:

https://youtrack.jetbrains.com/issue/CPP-11419

So it seems a problem related to CLion. :+1:
