### ISSUE TITLE
utringbuffer.h or ustringbuffer.h?

### ISSUE THREAD

**Issue by silvioprog** [troydhanson/uthash#140]
Hello.

I'm not sure if it was a type. The header is named as `utringbuffer.h`, but it seems the correct name would be `ustringbuffer.h`.

Thank you!

**Comment by tbeu** [comment]
It is a ring-buffer implementation. So it is correct as is.

**Comment by silvioprog** [comment]
Oops, you are right! It's ut-ring-buffer. :sweat_smile:
