### ISSUE TITLE
Disabling utstring specific features

### ISSUE THREAD

**Issue by silvioprog** [troydhanson/uthash#147]
Hello dudes.

Many GNU libraries allows to enable/disable any specific or extended features via  building system to generate smaller libraries even disabling the compiler optimizations. For example, in `libcurl` building, you can do `./configure --disable-cookies` before making it using `make install` -- it will generate and install a smaller `libcurl` without cookies support; in `libmicrohttpd`, you can use `./configure --disable-httpupgrade --disable-sendfile` before `make install-strip` and it will generate/install the smallest `libmicrohttp` without HTTP-Upgrade/SendFile support. And so on.

So, what do you think about to use this same approach in `utstring`? For example (notice `UTSTRING_FIND_DISABLED`):

```c
#ifndef UTSTRING_FIND_DISABLED

/*******************************************************************************
 * begin substring search functions                                            *
 ******************************************************************************/
/* Build KMP table from left to right. */
UTSTRING_UNUSED static void _utstring_BuildTable(

... the find feature stuff ...

    return V_FindPosition;
}
/*******************************************************************************
 * end substring search functions                                              *
 ******************************************************************************/

#endif /* UTSTRING_FIND_DISABLED */
```
then a programmer could do:

```c
#define UTSTRING_FIND_DISABLED 1
#include <utstring.h>

int main() {
...
```

or passing `-DUTSTRING_FIND_DISABLED=1` in their building system.

[I tested it in a library](https://github.com/risoflora/libbrook/blob/new_api/src/bk_str.c) and the final generated static library was 17.8 kB using `UTSTRING_FIND_DISABLED 1` against 22.4 kB in original way, even without informing any compiler optimization.

It would be very helpful a way to disable the `utstring-find` feature allowing `utstring` to be used for who that just wants as a stream structure replacement.

**Comment by Quuxplusone** [comment]
When you say "without informing [enabling?] any compiler optimization", that's a signal that your results aren't applicable to the real world. If you care about codegen size, you need to turn on `-O3`, at which point you'll see the unused functions disappear.

**Comment by silvioprog** [comment]
> [enabling?]

Yes.

> that's a signal that your results aren't applicable to the real world

Even in debug mode?

**Comment by Quuxplusone** [comment]
The examples you give from libcurl and microhttpd have nothing to do with debugging; they're locking down certain unsafe features for security reasons.

**Comment by silvioprog** [comment]
+1 Indeed. I tested enabling the compiler optimizations and the symbols disappears. Really makes no sense to add `UTSTRING_FIND_DISABLED`.
