### ISSUE TITLE
[vs2017] "conditional expression is constant"; "unreachable code uthash_bug"

### ISSUE THREAD

**Issue by silvioprog** [troydhanson/uthash#150]
Hello dudes.

I'm trying to compile a small library that uses `uthash.h`, but it raises some errors at build time on Visual Studio 2017 (the project declares the flags `/Wall /WX`).

The VS files was easily made by this cmake file:

`CMakeFile.txt`
```cmake
cmake_minimum_required(VERSION 3.5)
project(uthash_bug C)

set(CMAKE_C_STANDARD 99)

if (MSVC)
    set(CMAKE_C_FLAGS_RELEASE "${CMAKE_C_FLAGS_RELEASE} /Wall /WX /MT")
    set(CMAKE_C_FLAGS_DEBUG "${CMAKE_C_FLAGS_DEBUG} /Wall /WX")
endif ()

add_executable(uthash_bug
               uthash.h
               main.c)
if (MSVC_VERSION GREATER 1800)
    target_compile_definitions(uthash_bug PUBLIC _NO_CRT_STDIO_INLINE)
endif ()
```

and this command line:

```bash
mkdir build && cd build/ && cmake -G "Visual Studio 15 2017" ..
```

it generates all the required files for building the project on VS; just open the generated `uthash_bug.sln` and try to build the project in the VS (or, if you are an expert, just call the `CL` command by hand in the console).

First error:

```cmd
conditional expression is constant

C:\CLionProjects\uthash_bug\main.c	23
```
so, after commenting line 23:

```cmd
unreachable code

c:\clionprojects\uthash_bug\main.c	21
```

the code used in the example was:

```c
01. #include <string.h>
02. #include <stdlib.h>
03. #include <stdio.h>
04. #include "uthash.h"
05. 
06. struct my_struct {
07.     const char *name;
08.     int id;
09.     UT_hash_handle hh;
10. };
11. 
12. 
13. int main(void) {
14.     const char **n, *names[] = {"joe", "bob", "betty", NULL};
15.     struct my_struct *s, *tmp, *users = NULL;
16.     int i = 0;
17.     for (n = names; *n != NULL; n++) {
18.         s = (struct my_struct *) malloc(sizeof(struct my_struct));
19.         s->name = *n;
20.         s->id = i++;
21.         HASH_ADD_KEYPTR(hh, users, s->name, strlen(s->name), s);
22.     }
23.     HASH_FIND_STR(users, "betty", s);
24.     if (s) printf("betty's id is %d\n", s->id);
25.     HASH_ITER(hh, users, s, tmp) {
26.         HASH_DEL(users, s);
27.         free(s);
28.     }
29.     return 0;
30. }
```
I'm not macro expert, but I've tried to fix this problem anyway, however, any progress. :disappointed:

**Comment by silvioprog** [comment]
BTW I'm inclined to leave the ~~problematic~~ MS compiler. I've got many errors in other libraries I'm building in that too. It seems this compiler was done to difficult the life of the C programmer. Unfortunately.

I'll build `ut*` libraries (and other awesome GNU libraries) only in robust compilers like `gcc`/`clang`.

Sorry for the noising. :sweat_smile:

**Comment by silvioprog** [comment]
Phew, I left VS! However, I'll try to fix all errors reported by GCC's `-Wconversion` (this consequently solves the problems in VS, well... I think).

**Comment by tbeu** [comment]
I recommend to compile `cl /P /C main.c` to write the preprocessor output to main.i, copy the expanded macro from main.i back to main.c replacing the original macro calls. It also helps to add line breaks after the semicolons of the pasted code lines to have better compiler diagnostics of the relevant lines at the next run.
