### ISSUE TITLE
Any way to modify a value in a hash without deleting the key?

### ISSUE THREAD

**Issue by ddosDev** [troydhanson/uthash#153]
Hey there, I wanted to know if it would be possible to modify a value within a hash using the key to find it. I haven't found anything beside REPLACE macros.

**Comment by Quuxplusone** [comment]
Once you have the pointer to the element (via `FIND`), you can do whatever you want with it, right?

Of course, if while fiddling with the element, you accidentally change the element's key such that it is now in the "wrong" hash bucket, you're going to have a bad time.

Unless I'm brain-farting here, there is currently no supported way to "rehash-in-place" an element (that is, to change its `hh_prev`/`hh_next` pointers without also resetting its `prev`/`next` pointers and thus changing its place in the hash-table's iteration order).

**Comment by ddosDev** [comment]
Thank you so much for the answer and sorry for taking to long to close the issue!
