### ISSUE TITLE
Allow Murmur hash to be used unconditionally

### ISSUE THREAD

**Issue by nolange** [troydhanson/uthash#156]
Hello,

I wonder whether there are good reasons & examples why the `MUR_GETBLOCK` function cant be simplified to this:
(or even further, removing the GCC special case - the only upside would be that you don't need the `string.h` header and optimizations would work even when automatic built-ins are disabled).

```c
#ifdef __GNUC__
#define MUR_GETBLOCK(r, p,i) do { __builtin_memcpy(&r, &p[i], sizeof(r)); } while(0)
#else
#define MUR_GETBLOCK(p,i) do { memcpy(&r, &p[i], sizeof(r)); } while(0)
#endif

...

// And define _mur_blocks as byte-array (no cast to bigger alignment!),
// aswell as replacing the acces

const uint8_t *_mur_blocks = _mur_data+(_mur_nblocks*4);

...

MUR_GETBLOCK(_mur_k1, _mur_blocks,_mur_i * 4 );
```

The trick with strict aliasing is simply that you should always use `memcpy` to read/write unknown data. (everything else ain't strictly C conform). The compilers should do a fair job replacing this with a single 4byte read on all architectures that allow unaligned reads.

**Comment by Quuxplusone** [comment]
The MurmurHash code dates all the way back to the beginning of the repo (`git blame` points to 07bca4ce). I suspect it was cut-and-pasted from some MurmurHash reference implementation without much munging, which would explain just about any question beginning with "why". :)

Patches welcome. I personally am not going to originate any patch in that area.
A good step 1, actually, would be to add any _test_ for the MurmurHash code besides the very low-level `test62.c`.

**Comment by Quuxplusone** [comment]
`HASH_MUR` was removed in aa8d42d9c98fb8718d1c355ed65c659b4f323c62 (November 2019), so this issue is moot now.
