### ISSUE TITLE
sometimes, it cannot find by string hash key using HASH_FIND_STR

### ISSUE THREAD

**Issue by hqsh** [troydhanson/uthash#163]
In my code, when I use int hash key, it can always find the struct with the same exist key inserted in the uthash.
When use string hash key, when the count of struct inserted big enough (4000), sometimes it can find, but other times, it cannot find.
I found the hashval is correct (same as the inserted one), but the find result from HASH_FIND_IN_BKT is NULL. I don't know what happend in HASH_FIND_IN_BKT.
Is there any advice for debug it? Thank you!

**Comment by tbeu** [comment]
Is this reproducible? Can you share some test code?

**Comment by tbeu** [comment]
Hm, a unit test would be preferrable here.

**Comment by hqsh** [comment]
sorry, it's in developping. unit test will be in python code. i have found the reason and solved it. the string from mongodb should be memcpy, before insert into uthash. thanks.

**Comment by tbeu** [comment]
When I saw your  _CHAR_STRING_TO_UNI_CHAR_STRING yesterday, I actually wondered if string contains zeros or not. Glad you have it on your own.
