### ISSUE TITLE
Add example for HASH_ADD() with array as key

### ISSUE THREAD

**Issue by z3rone** [troydhanson/uthash#165]
An example of a `HASH_ADD()` call for an array-key one the website would be nice! Because it took me a long time to figure out, that you have to write `HASH_ADD(hh, root, key[0], key_len, target)` instead of `HASH_ADD(hh, root, key, key_len, target)`.

**Comment by Quuxplusone** [comment]
Hi @z3rone! Could you phrase this as a pull request against `doc/userguide.txt`?
Also, not as part of the PR but just for my own edification, please show a [short complete example](http://sscce.org) of the thing you tried that didn't work.
