### ISSUE TITLE
LL_FOREACH_SAFE2 

### ISSUE THREAD

**Issue by archerian** [troydhanson/uthash#179]
Hello,

I'm trying to understand what (el) && ((tmp) = (el)->next, 1) is supposed to do, can you please clarify? 

Thanks,

#define LL_FOREACH_SAFE2(head,el,tmp,next)                                                     \
  for ((el) = (head); (el) && ((tmp) = (el)->next, 1); (el) = (tmp))

**Comment by Quuxplusone** [comment]
This seems like a question better directed to your C/C++ instructor than to a uthash bug report. Looking at an operator precedence chart such as https://en.cppreference.com/w/c/language/expressions#Operators might help.
