### ISSUE TITLE
Is there any upperlimit about the size of key-value pairs?

### ISSUE THREAD

**Issue by lxyscls** [troydhanson/uthash#206]
Hello, I am looking for a hashtable to do some in-mem searching. I will put more than millions of pairs into it, so I am curious about is there any upperlimit? And I found that "Add, find and delete are normally constant-time operations.". How about the latency when resizing? Thank you.

**Comment by Quuxplusone** [comment]
Both the number of buckets in the table, and the number of items in the table, are represented with the `unsigned` type; so on a normal 32-bit system, the limit is about 4 billion items. On a 16-bit system, the limit is 65535 items.

Resizing (the operation spelled `HASH_EXPAND_BUCKETS` internally) requires rehashing every item, so it takes O(n).
