### ISSUE TITLE
Runtime error: dereferencing invalid pointer only when using tcc

### ISSUE THREAD

**Issue by kokizzu** [troydhanson/uthash#215]
I'm using this [code](https://github.com/kokizzu/kokizzu-benchmark/blob/master/assoc-small/uthash.c)
```
// uthash.c
#include <string.h>  /* strcpy */
#include <stdlib.h>  /* malloc */
#include <stdio.h>   /* printf */
#include "uthash.h"

const int MAX_DATA = 1230000;

struct kv {
	char *key;
	double val;
	UT_hash_handle hh;
};

char i2ch[] = {'0', '1', '2', '3', '4', '5', '6', '7', '8', '9', 'a', 'B', 'c', 'D', 'e', 'F'};

int get_first_digit(double d) {
	while(d > 10) {
		d /= 10;
	}
	return (int)(d);
}
char* to_rhex(int v) {
	char* hex = malloc(sizeof(char)*9); // because INT_MAX can be divided by 16 maximum 8 times
	memset(hex,0,9);
	int ctr = 0;
	while(v > 0) {
		hex[ctr++] = i2ch[v%16];
		v /= 16;
	}
	return hex;
}

char* to_str(int v) {
	int len = snprintf(NULL,0,"%d",v);
	char *res = malloc(len+1);
	snprintf(res, len+1, "%d", v);  
	return res;
}

int set_or_inc(struct kv** m, char* key, int set, int inc, int *ctr) {
	struct kv* item = 0;
	HASH_FIND_STR(*m, key, item);
	if(!item) {
		item = malloc(sizeof(*item));
		item->key = key;
		item->val = (double)(set);
		HASH_ADD_KEYPTR(hh, *m, item->key, strlen(item->key), item) ;
		return 0;
	} else {
		item->val += (double)(inc);
		*ctr += 1;
		return 1; // key not used
	}
}
int main() {
	struct kv *m = NULL;
	int dup1 =0, dup2 =0, dup3 =0;
	for(int z = MAX_DATA; z > 0; z--) {
		int val2 = MAX_DATA - z;
		int val3 = MAX_DATA*2 - z;
		char *key1 = to_str(z);
		char *key2 = to_str(val2);
		char *key3 = to_rhex(val3);
		if(set_or_inc(&m, key1, z, val2, &dup1)) free(key1);
		if(set_or_inc(&m, key2, val2, val3, &dup2)) free(key2);
		if(set_or_inc(&m, key3, val3, z, &dup3)) free(key3);
	}
	printf("%d %d %d\n",dup1, dup2, dup3);
	int total = 0, verify = 0, count = 0;
	struct kv *tmp, *item;
	HASH_ITER(hh, m, item, tmp) {
		total += get_first_digit(item->val);
		verify += strlen(item->key);
		count += 1;
		HASH_DEL(m,item);
		free(item->key);
		free(item);
	}
	printf("%d %d %d\n",total, verify, count);
}
```

when using tcc
```
time tcc -b -g -run uthash.c
bcheck.c __bound_ptr_indir8: 0x7fff3cd67ec8 is outside of the region
Runtime error: dereferencing invalid pointer
at 0x5626cfebe9b5 set_or_inc()
by 0x5626cfec15e9 main()
Command exited with non-zero status 255

CPU: 0.00s      Real: 0.00s     RAM: 3480KB
```

direct running (also pass when checked with `valgrind -s --track-origins=yes --keep-stacktraces=alloc-and-free`):
```
time tcc -run uthash.c
637912 641149 67002
3808703 14182513 2343937
Command exited with non-zero status 25

CPU: 2.52s      Real: 2.60s     RAM: 292144KB
```

when using gcc (even with `-fstack-protector-all`):
```
gcc uthash.c && time ./a.out
637912 641149 67002
3808703 14182513 2343937

CPU: 2.47s      Real: 2.57s     RAM: 290492KB
```

when using clang (even with `-fsanitize=address`):
```
clang uthash.c && time ./a.out
637912 641149 67002
3808703 14182513 2343937

CPU: 2.50s      Real: 2.59s     RAM: 290448KB
```

did I do something wrong?

**Comment by Quuxplusone** [comment]
Since you're using `HASH_FIND_STR`, I think it would be idiomatic to also replace

    HASH_ADD_KEYPTR(hh, *m, item->key, strlen(item->key), item) ;

with simply

    HASH_ADD_STR(*m, key, item);

(This shouldn't affect the actual issue, though.)
Is it possible that `malloc` is returning `NULL`? Add some `assert(ret != NULL)`, `assert(hex != NULL)`, `assert(item != NULL)`, etc., after all of your mallocs.

On a 64-bit platform, you're trying to allocate approximately 197'291'250 bytes (not counting what uthash is allocating for the hash table internally, which looks like about 50'331'712 bytes).

Is there anything weird about the platform where you're using `tcc`? From that 64-bit pointer value it _looks_ like x86-64, but if it's non-64-bit (like maybe a 32-bit platform), that would certainly be relevant. And if it's non-x86, well, I can't think of how that would cause your issue, but at least it'd be good to know.

**Comment by Quuxplusone** [comment]
Also, if this code is part of a benchmark, you should at least remove all the `int`->`double`->`int` conversions. Just stick with `int` or `size_t` for all your counters.

To _really_ "benchmark-ize" this code, I think you would make `key1` etc. into static char buffers:

    void set_or_inc(struct kv** m, const char* key, int set, int inc, int *ctr) {
        struct kv* item = 0;
        HASH_FIND_STR(*m, key, item);
        if(!item) {
            item = malloc(sizeof(*item));
            assert(item != NULL);
            item->key = strdup(key);  // malloc only at this point
            item->val = set;

    [...]
    const char* to_str(int v) {
        static char buffer[100];  // don't malloc here
        sprintf(buffer, "%d", v);
        return buffer;
    }

    [...]
                const char *key1 = to_str(z);
                set_or_inc(&m, key1, z, val2, &dup1);
                const char *key2 = to_str(val2);
                set_or_inc(&m, key2, val2, val3, &dup2);
                const char *key3 = to_rhex(val3);
                set_or_inc(&m, key3, val3, z, &dup3);

This way, whenever a key already appears in the hash, you don't waste time in `malloc` and `free`.

Also, you have an off-by-one error in your `get_first_digit` — it sometimes returns a first digit of `10`.

**Comment by kokizzu** [comment]
yes, it's 64-bit amd64

**Comment by Quuxplusone** [comment]
@kokizzu, any update on how to reproduce this issue? Any objection to my just closing it as "can't reproduce"?

**Comment by kokizzu** [comment]
nope, no problem
