### ISSUE TITLE
POSIX names

### ISSUE THREAD

**Issue by DBJDBJ** [troydhanson/uthash#216]
```
1>..\uthash\utarray.h(237,36): warning C4996: 'strdup': The POSIX name for this item is deprecated. Instead, use the ISO C and C++ conformant name: _strdup. See online help for details.
```

When using cl.exe  ... There are a few other occasions, `memset`, etc ...

**Comment by Quuxplusone** [comment]
POSIX is absolutely *not* deprecated. If MSVC is telling you it is, MSVC is wrong. Just turn off that warning.

Equally obviously, we're not going to stop using `memset` in C. ;)

**Comment by DBJDBJ** [comment]
Ugh, yes I know ...  :( 

some authors would do

```cpp
#ifndef UTHASH_STRDUP
#define UTHASH_STRDUP strdup
#endif 
```  

But yes, that would be succumbing to the pushers of the "Annex K" (laugh)

**Comment by Quuxplusone** [comment]
> some authors would do
>
>     #ifndef UTHASH_STRDUP
>     #define UTHASH_STRDUP strdup
>     #endif 

We do that for `uthash_malloc`, `uthash_free`, `uthash_bzero`, `uthash_strlen` in uthash.h; but that's more for the benefit of targets that don't have a libc at all, as opposed to platforms like MSVC that _have_ a perfectly functional libc but have developed some sort of weird love-hate relationship with their own library. 😛
