### ISSUE TITLE
New release v2.3.0?

### ISSUE THREAD

**Issue by tbeu** [troydhanson/uthash#223]
Because of 053bed12453660f2e2f7733438fc9312bc54adb5 I'm interested in a new release. Could you imaginge to create a new version in the near future? Thank you!

**Comment by tbeu** [comment]
Yes, that timelime is of course acceptable for me. Thanks a lot. That 053bed12453660f2e2f7733438fc9312bc54adb5 (388134a0d4387579be569ac32f7f7478c87f9e2c to be exact) was successfully tested in https://github.com/modelica/ModelicaStandardLibrary/pull/3728 in case you are interested.

**Comment by Quuxplusone** [comment]
Fixed by releasing v2.3.0 just now!
