### ISSUE TITLE
Is it feasible for application in MCU with limited RAM?

### ISSUE THREAD

**Issue by zrbruce** [troydhanson/uthash#235]
First the uthash is a very nice library. And I want to apply it into the MCU with limited RAM(< 256kB, 32bit), but the memory overhead seems a little costly. Is the current uthash feasible for this MCU use? Or any way to work around the RAM limitation for lib use?

**Comment by Quuxplusone** [comment]
IIUC, you're asking whether there's any macros or other techniques to make `sizeof(S)` any smaller than `36` here: https://godbolt.org/z/fKe4cYTGx
and the answer is "nope."
