### ISSUE TITLE
Question about LICENSE/COPYRIGHT

### ISSUE THREAD

**Issue by mufasachan** [troydhanson/uthash#262]
Hello,

I would like to add your source code to the typing practice web-tool [MonkeyType](https://github.com/monkeytypegame/monkeytype) which is under GPL-3.0 License. I want to add some templates and functions of your code. I do not want to add all your code. The addition of quotes is straightforward, a quote is an entry in a JSON file, see [here](https://github.com/monkeytypegame/monkeytype/blob/master/QUOTES.md#creating-quotes). In the `source`'s value I would add something like `uthash (Troy D. Hanson) - <file_name>`. 

Is it ok? Or should I ask to append the repo LICENSE file, or any other place, to include your ownership for these quotes?

Have a nice day.

**Comment by Quuxplusone** [comment]
Are you saying that you want to copy some of uthash's source code into
https://github.com/monkeytypegame/monkeytype/blob/master/frontend/static/quotes/code_c.json
as a sample for people to practice their typing skills?

There's plenty of public-domain software out there that you can copy (in part _or_ in whole) without running into licensing issues. I recommend that you stick to public-domain software. You don't need uthash for that.
GitHub even lets you search for "C code under the WTFPL": https://github.com/search?q=language%3AC+license%3Awtfpl&type=Repositories&ref=advsearch&l=C&l=

Likewise, there is _tons_ of public-domain literature in the world. You don't need to copy [the whole script of _Ratatouille_ but as a typing test](https://github.com/monkeytypegame/monkeytype/blob/master/frontend/static/challenges/littlechef.txt). Copy some Mark Twain, or the intertitles from a Harold Lloyd comedy, or _anything_ that's not encumbered by copyright. [The American Writers' Museum suggests:](https://americanwritersmuseum.org/new-works-to-enter-the-public-domain-in-2024/)

- Wanda Gág's _Millions of Cats_
- Edgar Rice Burroughs' _Tarzan, Lord of the Jungle_
- Franklin W. Dixon's _The Missing Chums_
- A.A. Milne's _The House at Pooh Corner_

Anyway, if you want to copy uthash's source code into your thing (even as a typing test), you should follow the instructions in [the LICENSE file](https://github.com/troydhanson/uthash/blob/master/LICENSE), which means including a copy of the license alongside your thing. (But you should no longer want to copy it. You should want to copy public-domain code instead.)
